steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/cpgateway:$COMMIT_SHA', '-t', 'gcr.io/$PROJECT_ID/cpgateway:latest', '.']
    id: 'build'

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cpgateway:$COMMIT_SHA']
    id: 'push-versioned'

  # Push the 'latest' tag
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/cpgateway:latest']
    id: 'push-latest'

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cpgateway-service'
      - '--image'
      - 'gcr.io/$PROJECT_ID/cpgateway:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--set-env-vars'
      - 'FLASK_ENV=production,SECRET_KEY=your-secret-key-here,SQLALCHEMY_DATABASE_URI=your-db-uri-here'
    id: 'deploy'

# Images created by the build
images:
  - 'gcr.io/$PROJECT_ID/cpgateway:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/cpgateway:latest'
