"""Add withdrawal_type and admin fields to withdrawal_requests

Revision ID: c13e49ad83e4
Revises: c6e381e09c54
Create Date: 2025-07-03 08:34:27.946914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c13e49ad83e4'
down_revision = 'c6e381e09c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal_type', sa.Enum('USER_REQUEST', 'CLIENT_BALANCE', name='withdrawaltype'), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejection_reason', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('fee', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('net_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('user_wallet_address', sa.String(length=100), nullable=True))
        batch_op.create_foreign_key('fk_withdrawal_requests_user_id', 'users', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_withdrawal_requests_approved_by', 'admin_users', ['approved_by'], ['id'])
        batch_op.create_foreign_key('fk_withdrawal_requests_rejected_by', 'admin_users', ['rejected_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('withdrawal_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_withdrawal_requests_rejected_by', type_='foreignkey')
        batch_op.drop_constraint('fk_withdrawal_requests_approved_by', type_='foreignkey')
        batch_op.drop_constraint('fk_withdrawal_requests_user_id', type_='foreignkey')
        batch_op.drop_column('user_wallet_address')
        batch_op.drop_column('user_id')
        batch_op.drop_column('net_amount')
        batch_op.drop_column('fee')
        batch_op.drop_column('rejection_reason')
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('withdrawal_type')

    # ### end Alembic commands ###
        batch_op.drop_column('rejected_by')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('withdrawal_type')

    # ### end Alembic commands ###
