"""Add username column to clients table

Revision ID: c6e381e09c54
Revises: 20250701_add_currency_models
Create Date: 2025-07-03 00:44:29.009061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e381e09c54'
down_revision = '20250701_add_currency_models'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=50), nullable=True))
        batch_op.create_unique_constraint('uq_clients_username', ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clients', schema=None) as batch_op:
        batch_op.drop_constraint('uq_clients_username', type_='unique')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
